# Generated by Django 3.2.5 on 2021-08-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smilaMusicSite', '0002_studentrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drums', models.CharField(max_length=200)),
                ('e_guitar', models.CharField(max_length=200)),
                ('bass_guitar', models.CharField(max_length=200)),
                ('vocals', models.CharField(max_length=200)),
                ('piano', models.CharField(max_length=200)),
            ],
        ),
    ]
